### ISSUE TITLE
monero- trouble with wallet

### ISSUE THREAD

**Issue by nickpatelstore** [creating2morrow/neveko#29]
trying to install wallet.

I received error sayin Daemon failed to start.

unknown error

please check your wallet and daemon log for errors. you can also try to start monerod.exe manually

what to do?

**Comment by creating2morrow** [comment]
There is no development support for windows. Only Linux currently. Please try with a vm such as VirtualBox.

**Comment by nickpatelstore** [comment]
but on getmonero you can download monero for windows
