### ISSUE TITLE
i2p-zero http proxy

### ISSUE THREAD

**Issue by creating2morrow** [creating2morrow/neveko#4]
always getting `destination lease set not found` unless using i2pd http proxy

**Comment by creating2morrow** [comment]
needed to run a new build.

https://github.com/creating2morrow/i2p-zero/releases/v1.21-nevmes

**Comment by k4r4b3y** [comment]
Why is i2p-zero chosen for neveko? Can it work with i2pd instead?

**Comment by creating2morrow** [comment]
> Why is i2p-zero chosen for neveko? Can it work with i2pd instead?

it doesn't matter. i2p-zero is just a wrap. you can use any i2p instance. neveko uses i2p-zero to abstract all i2p tunnel creation away for normal users. power users can configure their own i2p proxy server through advanced settings.

https://github.com/creating2morrow/neveko/issues/22
